import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import Transitions from "./context/loading/loadingLink";
import Animate from "@/modules/transition/Animate";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased overflow-hidden`}
      >
        <Transitions>
          <Animate>
            {children}
          </Animate>
        </Transitions>
      </body>
    </html>
  );
}
